# Include this file from your Apache server configuration after the module
# loader in conf.modules.d/10-mod_apex.conf.
ApexVerboseErrors Off

<FilesMatch \.php$>
    SetHandler php-script
</FilesMatch>
