#!/usr/bin/env bash
set -euo pipefail

sizing_lib="${APEX_SIZING_LIB:-/usr/local/lib/php-apex/apex-sizing.sh}"
if [[ ! -r "$sizing_lib" ]]; then
    echo "PHP Apex sizing helper was not found: $sizing_lib" >&2
    exit 66
fi
# shellcheck source=../packaging/apex-sizing.sh
source "$sizing_lib"

runtime_conf="${APEX_RUNTIME_CONF:-/etc/apache2/conf-available/apex-runtime.conf}"
opcache_conf="${APEX_OPCACHE_CONF:-/usr/local/php-zts/etc/conf.d/99-apex-runtime.ini}"
test_page_source="${APEX_TEST_PAGE_SOURCE:-/usr/local/share/mod-apex/test.php}"
test_page_target="${APEX_TEST_PAGE_TARGET:-/var/www/html/test.php}"

is_positive_integer() {
    [[ "${1:-}" =~ ^[1-9][0-9]*$ ]]
}

is_nonnegative_integer() {
    [[ "${1:-}" =~ ^(0|[1-9][0-9]*)$ ]]
}

workers=""
keep_alive="${APEX_KEEP_ALIVE:-0}"
opcache_validate="${APEX_OPCACHE_VALIDATE:-0}"
allow_url_fopen="${APEX_ALLOW_URL_FOPEN:-1}"
disable_functions="${APEX_DISABLE_FUNCTIONS:-}"
enable_test_page="${APEX_ENABLE_TEST_PAGE:-0}"
max_connections_per_child="${APEX_MAX_CONNECTIONS_PER_CHILD:-0}"
trusted_proxy_value="${APEX_TRUSTED_PROXY:-}"
trusted_proxies=()

if [[ "$opcache_validate" != "0" && "$opcache_validate" != "1" ]]; then
    echo "PHP Apex: APEX_OPCACHE_VALIDATE must be 0 or 1." >&2
    exit 64
fi

if [[ "$allow_url_fopen" != "0" && "$allow_url_fopen" != "1" ]]; then
    echo "PHP Apex: APEX_ALLOW_URL_FOPEN must be 0 or 1." >&2
    exit 64
fi

if [[ "$enable_test_page" != "0" && "$enable_test_page" != "1" ]]; then
    echo "PHP Apex: APEX_ENABLE_TEST_PAGE must be 0 or 1." >&2
    exit 64
fi

if [[ "$keep_alive" != "0" && "$keep_alive" != "1" ]]; then
    echo "PHP Apex: APEX_KEEP_ALIVE must be 0 or 1." >&2
    exit 64
fi
if [[ "$keep_alive" == "1" ]]; then
    keep_alive_directive="On"
else
    keep_alive_directive="Off"
fi

if [[ -n "$disable_functions" ]] &&
   [[ ! "$disable_functions" =~ ^[A-Za-z_][A-Za-z0-9_]*(,[A-Za-z_][A-Za-z0-9_]*)*$ ]]; then
    echo "PHP Apex: APEX_DISABLE_FUNCTIONS must be a comma-separated list of PHP function names." >&2
    exit 64
fi

if ! is_nonnegative_integer "$max_connections_per_child" ||
   (( ${#max_connections_per_child} > 7 )) ||
   (( 10#$max_connections_per_child > 1000000 )); then
    echo "PHP Apex: APEX_MAX_CONNECTIONS_PER_CHILD must be a whole number from 0 to 1000000." >&2
    exit 64
fi

if [[ -n "$trusted_proxy_value" ]]; then
    if [[ "$trusted_proxy_value" == *$'\n'* ||
          "$trusted_proxy_value" == *$'\r'* ||
          "$trusted_proxy_value" == *$'\t'* ]]; then
        echo "PHP Apex: APEX_TRUSTED_PROXY must contain only space-separated IP addresses or CIDR ranges." >&2
        exit 64
    fi
    read -r -a trusted_proxies <<< "$trusted_proxy_value"
    if (( ${#trusted_proxies[@]} == 0 )); then
        echo "PHP Apex: APEX_TRUSTED_PROXY must contain only space-separated IP addresses or CIDR ranges." >&2
        exit 64
    fi
    for proxy in "${trusted_proxies[@]}"; do
        if [[ ! "$proxy" =~ ^[0-9A-Fa-f:.]+(/[0-9]{1,3})?$ ]]; then
            echo "PHP Apex: APEX_TRUSTED_PROXY must contain only space-separated IP addresses or CIDR ranges." >&2
            exit 64
        fi
    done
fi

if [[ -n "${APEX_MAX_REQUEST_WORKERS:-}" ]]; then
    workers="$APEX_MAX_REQUEST_WORKERS"
    if ! is_positive_integer "$workers" || (( workers < 1 || workers > 512 )); then
        echo "PHP Apex: APEX_MAX_REQUEST_WORKERS must be a whole number from 1 to 512." >&2
        exit 64
    fi
else
    apex_calculate_auto_sizing || exit $?
    workers="$apex_workers"
fi

requested_workers=$workers
apex_calculate_mpm_layout "$workers" 1 || exit $?
workers=$apex_mpm_workers
threads_per_child=$apex_mpm_threads_per_child
server_limit=$apex_mpm_server_limit
start_servers=$apex_mpm_start_servers
min_spare_threads=$apex_mpm_min_spare_threads
max_spare_threads=$apex_mpm_max_spare_threads
if (( workers != requested_workers )); then
    echo "PHP Apex: adjusted worker limit from ${requested_workers} to ${workers} for a valid event-MPM layout."
fi

install -d -m 0755 "$(dirname "$runtime_conf")"
cat > "$runtime_conf" <<EOF
# Generated by PHP Apex at container start. Do not edit this file.
KeepAlive ${keep_alive_directive}
MaxKeepAliveRequests 10000
KeepAliveTimeout 1

<IfModule mpm_event_module>
    StartServers ${start_servers}
    ServerLimit ${server_limit}
    ThreadLimit ${threads_per_child}
    ThreadsPerChild ${threads_per_child}
    MinSpareThreads ${min_spare_threads}
    MaxSpareThreads ${max_spare_threads}
    MaxRequestWorkers ${workers}
    MaxConnectionsPerChild ${max_connections_per_child}
</IfModule>
EOF

if (( ${#trusted_proxies[@]} > 0 )); then
    {
        echo '<IfModule remoteip_module>'
        echo '    RemoteIPHeader X-Forwarded-For'
        for proxy in "${trusted_proxies[@]}"; do
            printf '    RemoteIPTrustedProxy %s\n' "$proxy"
        done
        echo '</IfModule>'
    } >> "$runtime_conf"
fi

install -d -m 0755 "$(dirname "$opcache_conf")"
cat > "$opcache_conf" <<EOF
; Generated by PHP Apex at container start. Do not edit this file.
opcache.validate_timestamps=${opcache_validate}
expose_php=Off
session.cookie_httponly=1
session.cookie_samesite=Lax
allow_url_fopen=${allow_url_fopen}
disable_functions=${disable_functions}
EOF

if [[ "$enable_test_page" == "1" ]]; then
    if [[ ! -f "$test_page_source" ]]; then
        echo "PHP Apex: test page source not found: ${test_page_source}" >&2
        exit 66
    fi
    install -d -m 0755 "$(dirname "$test_page_target")"
    install -m 0644 "$test_page_source" "$test_page_target"
fi

if [[ -n "${APEX_MAX_REQUEST_WORKERS:-}" ]]; then
    sizing_summary="operator worker override"
else
    sizing_summary="${apex_cpu_count} CPU, ${apex_memory_mb} MiB, limited by ${apex_limiting_resource}"
fi
echo "PHP Apex: ${workers} maximum request workers (${sizing_summary}), keep-alive ${keep_alive_directive}, ${max_connections_per_child} connections per child, OPcache timestamp validation ${opcache_validate}, URL fopen ${allow_url_fopen}."

if [[ "${1:-}" == "apache2ctl" ]]; then
    apache2ctl -t
fi

exec "$@"
